package edu.gatech.model.enumvalueset;

public enum FIPSCountryCodes implements BaseSerialEnum{
    CROATIA("HR", "Croatia"),
    CUBA("CU", "Cuba"),
    CURACAO("CW", "Curacao"),
    CYPRUS("CY", "Cyprus"),
    CZECH_REPUBLIC("CZ", "Czech Republic"),
    DENMARK("DK", "Denmark"),
    DHEKELIA("-", "Dhekelia"),
    DJIBOUTI("DJ", "Djibouti"),
    DOMINICA("DM", "Dominica"),
    DOMINICAN_REPUBLIC("DO", "Dominican Republic"),
    ECUADOR("EC", "Ecuador"),
    EGYPT("EG", "Egypt"),
    EL_SALVADOR("SV", "El Salvador"),
    EQUATORIAL_GUINEA("GQ", "Equatorial Guinea"),
    ERITREA("ER", "Eritrea"),
    ESTONIA("EE", "Estonia"),
    ETHIOPIA("ET", "Ethiopia"),
    ETOROFU_HABOMAI_KUNASHIRI_SHIKOTAN_ISLANDS("-", "Etorofu, Habomai, Kunashiri, and Shikotan Islands"),
    EUROPA_ISLAND("RE", "Europa Island"),
    FALKLAND_ISLANDS("FK", "Falkland Islands (Islas Malvinas)"),
    FAROE_ISLANDS("FO", "Faroe Islands"),
    FIJI("FJ", "Fiji"),
    FINLAND("FI", "Finland"),
    FRANCE("FR", "France"),
    FRANCE_METROPOLITAN("FX", "France, Metropolitan"),
    FRENCH_GUIANA("GF", "French Guiana"),
    FRENCH_POLYNESIA("PF", "French Polynesia"),
    FRENCH_SOUTHERN_ANTARCTIC_LANDS("TF", "French Southern and Antarctic Lands"),
    GABON("GA", "Gabon"),
    GAMBIA("GM", "Gambia, The"),
    GAZA_STRIP("PS", "Gaza Strip"),
    GEORGIA("GE", "Georgia"),
    GERMANY("DE", "Germany"),
    GHANA("GH", "Ghana"),
    GIBRALTAR("GI", "Gibraltar"),
    GLORIOSO_ISLANDS("RE", "Glorioso Islands"),
    GREECE("GR", "Greece"),
    GREENLAND("GL", "Greenland"),
    GRENADA("GD", "Grenada"),
    GUADELOUPE("GP", "Guadeloupe"),
    GUAM("GU", "Guam"),
    GUATEMALA("GT", "Guatemala"),
    GUERNSEY("GB", "Guernsey"),
    GUINEA("GN", "Guinea"),
    GUINEA_BISSAU("GW", "Guinea-Bissau"),
    GUYANA("GY", "Guyana"),
    HAITI("HT", "Haiti"),
    HEARD_ISLAND_MCDONALD_ISLANDS("HM", "Heard Island and McDonald Islands"),
    HONDURAS("HN", "Honduras"),
    HONG_KONG("HK", "Hong Kong"),
    HOWLAND_ISLAND("UM", "Howland Island"),
    HUNGARY("HU", "Hungary"),
    ICELAND("IS", "Iceland"),
    INDIA("IN", "India"),
    INDONESIA("ID", "Indonesia"),
    IRAN("IR", "Iran"),
    IRAQ("IQ", "Iraq"),
    IRELAND("IE", "Ireland"),
    ISLE_OF_MAN("GB", "Isle of Man"),
    ISRAEL("IL", "Israel"),
    ITALY("IT", "Italy"),
    JAMAICA("JM", "Jamaica"),
    JAN_MAYEN("SJ", "Jan Mayen"),
    JAPAN("JP", "Japan"),
    JARVIS_ISLAND("UM", "Jarvis Island"),
    JERSEY("GB", "Jersey"),
    JOHNSTON_ATOLL("UM", "Johnston Atoll"),
    JORDAN("JO", "Jordan"),
    JUAN_DE_NOVA_ISLAND("RE", "Juan de Nova Island"),
    KAZAKHSTAN("KZ", "Kazakhstan"),
    KENYA("KE", "Kenya"),
    KINGMAN_REEF("UM", "Kingman Reef"),
    KIRIBATI("KI", "Kiribati"),
    KOREA_NORTH("KP", "Korea, North"),
    KOREA_SOUTH("KR", "Korea, South"),
    KOSOVO("-", "Kosovo"),
    KUWAIT("KW", "Kuwait"),
    KYRGYZSTAN("KG", "Kyrgyzstan"),
    LAOS("LA", "Laos"),
    LATVIA("LV", "Latvia"),
    LEBANON("LB", "Lebanon"),
    LESOTHO("LS", "Lesotho"),
    LIBERIA("LR", "Liberia"),
    LIBYA("LY", "Libya"),
    LIECHTENSTEIN("LI", "Liechtenstein"),
    LITHUANIA("LT", "Lithuania"),
    LUXEMBOURG("LU", "Luxembourg"),
    MACAU("MO", "Macau"),
    MACEDONIA("MK", "Macedonia"),
    MADAGASCAR("MG", "Madagascar"),
    MALAWI("MW", "Malawi"),
    MALAYSIA("MY", "Malaysia"),
    MALDIVES("MV", "Maldives"),
    MALI("ML", "Mali"),
    MALTA("MT", "Malta"),
    MARSHALL_ISLANDS("MH", "Marshall Islands"),
    MARTINIQUE("MQ", "Martinique"),
    MAURITANIA("MR", "Mauritania"),
    MAURITIUS("MU", "Mauritius"),
    MAYOTTE("YT", "Mayotte"),
    MEXICO("MX", "Mexico"),
    MICRONESIA_FEDERATED_STATES_OF("FM", "Micronesia, Federated States of"),
    MIDWAY_ISLANDS("UM", "Midway Islands"),
    MOLDOVA("MD", "Moldova"),
    MONACO("MC", "Monaco"),
    MONGOLIA("MN", "Mongolia"),
    MONTENEGRO("ME", "Montenegro"),
    MONTSERRAT("MS", "Montserrat"),
    MOROCCO("MA", "Morocco"),
    MOZAMBIQUE("MZ", "Mozambique"),
    MYANMAR("MM", "Myanmar"),
    NAMIBIA("NA", "Namibia"),
    NAURU("NR", "Nauru"),
    NAVASSA_ISLAND("UM", "Navassa Island"),
    NEPAL("NP", "Nepal"),
    NETHERLANDS("NL", "Netherlands"),
    NEW_CALEDONIA("NC", "New Caledonia"),
    NEW_ZEALAND("NZ", "New Zealand"),
    NICARAGUA("NI", "Nicaragua"),
    NIGER("NE", "Niger"),
    NIGERIA("NG", "Nigeria"),
    NIUE("NU", "Niue"),
    NORFOLK_ISLAND("NF", "Norfolk Island"),
    NORTHERN_MARIANA_ISLANDS("MP", "Northern Mariana Islands"),
    NORWAY("NO", "Norway"),
    OMAN("OM", "Oman"),
    PAKISTAN("PK", "Pakistan"),
    PALAU("PW", "Palau"),
    PALMYRA_ATOLL("UM", "Palmyra Atoll"),
    PANAMA("PA", "Panama"),
    PAPUA_NEW_GUINEA("PG", "Papua New Guinea"),
    PARACEL_ISLANDS("-", "Paracel Islands"),
    PARAGUAY("PY", "Paraguay"),
    PERU("PE", "Peru"),
    PHILIPPINES("PH", "Philippines"),
    PITCAIRN_ISLANDS("PN", "Pitcairn Islands"),
    POLAND("PL", "Poland"),
    PORTUGAL("PT", "Portugal"),
    PUERTO_RICO("PR", "Puerto Rico"),
    QATAR("QA", "Qatar"),
    REUNION("RE", "Reunion"),
    ROMANIA("RO", "Romania"),
    RUSSIA("RU", "Russia"),
    RWANDA("RW", "Rwanda"),
    SAINT_BARTHELEMY("BL", "Saint Barthelemy"),
    SAINT_HELENA("SH", "Saint Helena"),
    SAINT_KITTS_AND_NEVIS("KN", "Saint Kitts and Nevis"),
    SAINT_LUCIA("LC", "Saint Lucia"),
    SAINT_MARTIN("MF", "Saint Martin"),
    SAINT_PIERRE_AND_MIQUELON("PM", "Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "Saint Vincent and the Grenadines"),
    SAMOA("WS", "Samoa"),
    SAN_MARINO("SM", "San Marino"),
    SAO_TOME_AND_PRINCIPE("ST", "Sao Tome and Principe"),
    SAUDI_ARABIA("SA", "Saudi Arabia"),
    SENEGAL("SN", "Senegal"),
    SERBIA("RS", "Serbia"),
    SEYCHELLES("SC", "Seychelles"),
    SIERRA_LEONE("SL", "Sierra Leone"),
    SINGAPORE("SG", "Singapore"),
    SINT_MAARTEN("SX", "Sint Maarten"),
    SLOVAKIA("SK", "Slovakia"),
    SLOVENIA("SI", "Slovenia"),
    SOLOMON_ISLANDS("SB", "Solomon Islands"),
    SOMALIA("SO", "Somalia"),
    SOUTH_AFRICA("ZA", "South Africa"),
    SOUTH_GEORGIA_AND_THE_ISLANDS("GS", "South Georgia and the Islands"),
    SOUTH_SUDAN("SS", "South Sudan"),
    SPAIN("ES", "Spain"),
    SPRATLY_ISLANDS("-", "Spratly Islands"),
    SRI_LANKA("LK", "Sri Lanka"),
    SUDAN("SD", "Sudan"),
    SURINAME("SR", "Suriname"),
    SVALBARD("SJ", "Svalbard"),
    SWAZILAND("SZ", "Swaziland"),
    SWEDEN("SE", "Sweden"),
    SWITZERLAND("CH", "Switzerland"),
    SYRIA("SY", "Syria"),
    TAIWAN("TW", "Taiwan"),
    TAJIKISTAN("TJ", "Tajikistan"),
    TANZANIA("TZ", "Tanzania"),
    THAILAND("TH", "Thailand"),
    TIMOR_LESTE("TL", "Timor-Leste"),
    TOGO("TG", "Togo"),
    TOKELAU("TK", "Tokelau"),
    TONGA("TO", "Tonga"),
    TRINIDAD_AND_TOBAGO("TT", "Trinidad and Tobago"),
    TROMELIN_ISLAND("UM", "Tromelin Island"),
    TUNISIA("TN", "Tunisia"),
    TURKEY("TR", "Turkey"),
    TURKMENISTAN("TM", "Turkmenistan"),
    TURKS_AND_CAICOS_ISLANDS("TC", "Turks and Caicos Islands"),
    TUVALU("TV", "Tuvalu"),
    UGANDA("UG", "Uganda"),
    UKRAINE("UA", "Ukraine"),
    UNITED_ARAB_EMIRATES("AE", "United Arab Emirates"),
    UNITED_KINGDOM("GB", "United Kingdom"),
    UNITED_STATES("US", "United States"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("UM", "United States Minor Outlying Islands"),
    URUGUAY("UY", "Uruguay"),
    UZBEKISTAN("UZ", "Uzbekistan"),
    VANUATU("VU", "Vanuatu"),
    VATICAN_CITY("VA", "Vatican City"),
    VENEZUELA("VE", "Venezuela"),
    VIETNAM("VN", "Vietnam"),
    VIRGIN_ISLANDS_BRITISH("VG", "Virgin Islands, British"),
    VIRGIN_ISLANDS_US("VI", "Virgin Islands, U.S."),
    VIRGIN_ISLANDS_UK("-", "Virgin Islands (UK)"),
    VIRGIN_ISLANDS_US2("-", "Virgin Islands (US)"), //Note strange value
    WAKE_ISLAND("UM", "Wake Island"),
    WALLIS_AND_FUTUNA("WF", "Wallis and Futuna"),
    WEST_BANK("PS", "West Bank"),
    WESTERN_SAHARA("EH", "Western Sahara"),
    WESTERN_SAMOA("-", "Western Samoa"),
    WORLD("-", "World"),
    YEMEN("YE", "Yemen"),
    ZAIRE("-", "Zaire"),
    ZAMBIA("ZM", "Zambia"),
    ZIMBABWE("ZW", "Zimbabwe");

    private final String code;
    private final String description;

    FIPSCountryCodes(String code, String description) {
        this.code = code;
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public String getDescription() {
        return description;
    }

    public String toString(){
        return code;
    }
}
